### ISSUE TITLE
about experiments

### ISSUE THREAD

**Issue by peacockshit** [YilinLiu97/FasterDIP-devil-in-upsampling#1]
May I ask how can I reproduce the results in your Table 2?

**Comment by YilinLiu97** [comment]
Hi,  we are still working to clean up the code. But for now, to replicate the results, you can simply set the "--archi_type DIP_2_scaled", and set "num_scales=2", then set "dim" according to the width label associated with the images ("Texture-DIP/NoRepeated"), since these images have been pre-classified.  

Hope it helps.

**Comment by peacockshit** [comment]
Thanks for your answer, it does help a lot.
